[Metal] Allow double for vararg
JuliaGPU/GPUCompiler.jl pull request #630
Opened 2024-09-17 10:33 UTC by tgymnich

Allow double for C's default argument promotions used in variable-length argument lists.

needed for https://github.com/JuliaGPU/Metal.jl/pull/418

2024-09-17 10:36 UTC, maleadt commented
Are there any other uses for double that are legal? If not, I'd rather we somehow whitelist the `printf` handling, because the existing error reporting is _much_ more user friendly than the otherwise completely opaque compilation errors as reported by Metal's back-end compiler.

2024-09-17 10:39 UTC, tgymnich commented
Use of `double` for logging currently consists of `fpext` and a `store`

2024-09-17 12:00 UTC, maleadt commented
> Maybe we can tag it with some metadata?

Yeah, if it survives optimization. Or, alternatively, a function attribute (`julia.allow_double`) set on the `@noinline` body of the `printf` code doing the `fpext` etc? That may be more robust.

2024-09-19 02:25 UTC, christiangnrd commented on src/metal.jl
>      # Metal never supports double precision
No longer accurate?

2024-09-19 08:33 UTC, maleadt requested changes
After some testing, I don't think metadata is going to work. In any case, it's the wrong tool for the job. We could devise more elaborate IR patterns that do survive, but I don't see the value in that.

Let's just not use `check_ir_values`, which is a simple enough function, and instead roll our own version in `metal.jl` which ignores the `fpext`/`store`. Or, if you feel fancy, maybe a `allow_cb` callback argument to `check_ir_values`.

2024-09-20 13:24 UTC, maleadt commented
Maybe add a simple test with pre-defined IR modules to check this behavior (`double` normally disallowed, only when passed to logging)?

2024-09-20 17:05 UTC, maleadt approved these changes

2024-09-21 10:53 UTC, maleadt approved these changes

2024-09-21 11:24 UTC, merged